version: 2.1
jobs:
  build-n-push:
    docker:
      - image: 'circleci/golang:latest'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Images
          command: |
            TAGSUFFIX=$(date +%Y%m%d)
            export CONTAINER_TAG=vl3_latest
            export CONTAINER_REPO=${DOCKER_ORG:-$DOCKER_USER}
            make k8s-build

            nsmimgs=($(docker images | grep -E "${CONTAINER_TAG}" | awk '{ print $1 }'))
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            for img in ${nsmimgs[@]}; do
              echo "--- pushing ${img}:${CONTAINER_TAG} and ${img}:${CONTAINER_TAG}-${TAGSUFFIX}"
              docker tag ${img} ${img}:${CONTAINER_TAG}
              docker push ${img}:${CONTAINER_TAG}
              docker tag ${img} ${img}:${CONTAINER_TAG}-${TAGSUFFIX}
              docker push ${img}:${CONTAINER_TAG}-${TAGSUFFIX}
            done
workflows:
  build-n-push:
    jobs:
      - build-n-push:
          context: nse-publish
          filters:
            branches:
              only:
                - vl3_latest