version: 2.1

defaults: &defaults
  working_directory: /go/src/github.com/cisco-app-networking/networkservicemesh
  docker:
    - image: circleci/golang:latest

commands:
  publish-steps:
    parameters:
      tag:
        type: string
        default: vl3_latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Publish Images
          command: |
            export CONTAINER_TAG=<< parameters.tag >>
            echo "Tag for images: ${CONTAINER_TAG}"
            TAGSUFFIX=$(date +%Y%m%d)
            export CONTAINER_REPO=${DOCKER_ORG:-$DOCKER_USER}
            make k8s-build

            nsmimgs=($(docker images | grep -E "${CONTAINER_TAG}" | awk '{ print $1 }'))
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
            for img in ${nsmimgs[@]}; do
              echo "--- pushing ${img}:${CONTAINER_TAG} and ${img}:${CONTAINER_TAG}-${TAGSUFFIX}"
              docker tag ${img} ${img}:${CONTAINER_TAG}
              docker push ${img}:${CONTAINER_TAG}
              docker tag ${img} ${img}:${CONTAINER_TAG}-${TAGSUFFIX}
              docker push ${img}:${CONTAINER_TAG}-${TAGSUFFIX}
            done

jobs:
  publish-vl3_latest:
    <<: *defaults
    steps:
      - publish-steps

  publish-tagged-images:
    <<: *defaults
    steps:
      - publish-steps:
          tag: ${CIRCLE_TAG}

workflows:
  build-n-push:
    jobs:
      - publish-vl3_latest:
          context: nse-publish
          filters:
            branches:
              only:
                - vl3_latest
      - publish-tagged-images:
          context: nse-publish
          filters:
            branches:
              ignore: /.*/ # will run only for git tagged commits
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+-vl3/
